### ISSUE TITLE
Support CSS styles for Material UI theme

### ISSUE THREAD

**Issue by novabyte** [yacir/markdown-fenced-code-tabs#8]
I'm trying to use this extension with a project which uses Material UI via [mkdocs-material](https://github.com/squidfunk/mkdocs-material). It looks like the HTML generated for use with Twitter Bootstrap to create code tabs isn't the same rough layout as what the HTML with Material UI would expect. What's the best way to make changes?

Should I fork the repo and would the changes be accepted upstream with some kind of flag to switch themes?

**Comment by yacir** [comment]
You could simply add an `extra-css` to your `mkdocs.yml`: 

```yml
extra_css:
  - THE-PATH/code-tabs.css
```

The `code-tabs.css` content :

```css
.code-nav-container {
  background: #fff;
  border: 1px solid #ebebeb;
  margin: 16px 0;
}

.code-nav-container > .nav-tabs {
  padding: 0;
  margin: 0;
  list-style: none;
  border-bottom: 1px solid #ebebeb;
  height: 48px;
  white-space: nowrap;
}

.code-nav-container > .nav-tabs > li {
  position: relative;
  display: inline-block;
  border-bottom: 2px solid transparent;
  border-top: 2px solid transparent;
  height: 47px;
  max-width: 200px;
  margin: 0;
  overflow: hidden;
  padding: 0 24px;
  text-align: center;
  text-overflow: ellipsis;
  text-transform: uppercase;
  white-space: nowrap;
}

.code-nav-container > .nav-tabs > li.active {
  border-bottom-color: #039be5;
}

.code-nav-container > .nav-tabs > li > a {
  color: #757575;
  font: 500 14px/43px sans-serif;
}

.code-nav-container > .nav-tabs > li > a:hover,
.code-nav-container > .nav-tabs > li > a:focus,
.code-nav-container > .nav-tabs > li.active > a,
.code-nav-container > .nav-tabs > li.active > a:hover,
.code-nav-container > .nav-tabs > li.active > a:focus {
  text-decoration: none;
  color: #039be5;
}

.code-nav-container > .tab-content > .tab-pane {
  display: none;
}

.code-nav-container > .tab-content > .active {
  display: block;
}

.code-nav-container > .tab-content > .tab-pane:before {
    content: none !important;
}

.code-nav-container > .tab-content > .tab-pane > .codehilite {
    margin-top: 0px;
    margin-bottom: 0px;
}
```
